enum events {
  JOIN_GAME = "JOIN GAME",
  UPDATE_GAME = "UPDATE GAME",
  CHAT_MESSAGE = "CHAT MESSAGEs",
  MOVE = "MOVE",
  NEW_GAME = "NEW GAME",
  RESIGNATION = "RESIGNATION",
  DRAW_OFFER = "DREAW OFFER",
  DECLINE_DRAW = "DREAW OFFER",
  ACCEPT_DRAW = "ACCEPT DRAW",
  EXIT_GAME = "EXIT GAME",
  GAME_OVER = "GAME OVER",
  DISCONECT = "disconnect",
}

export default events;
