enum gameActionType {
  JOIN_GAME = "JOIN GAME",
  MOVE = "MOVE",
  UPDATE_BOARD = "UPDATE BOARD",
  NEW_GAME = "NEW GAME",
  RESIGNATION = "RESIGNATION",
  DRAW_OFFER = "DREAW OFFER",
  DECLINE_DRAW = "DREAW OFFER",
  ACCEPT_DRAW = "ACCEPT DRAW",
  EXIT_GAME = "EXIT GAME",
  GAME_OVER = "GAME OVER",
  DISCONECT = "disconnect",
}

export default gameActionType;
